---
name: CI checks

on:
  workflow_dispatch:
    inputs:
      source:
        description: Source ref used to build bindings. Uses `github.ref`` by default.
        required: false
      sha:
        description: Source SHA used to build bindings. Uses `github.sha`` by default.
        required: false
  push:
    branches:
    - main
    paths:
    - action.yaml
    - endpoint.py
    - tests.py
    - .github/workflows/tests.yaml
    - .github/ci-tools.toml
  pull_request:
    paths:
    - action.yaml
    - endpoint.py
    - tests.py
    - .github/workflows/tests.yaml
    - .github/ci-tools.toml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v5.0.2
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
        key: ${{ runner.os }}-${{ inputs.cache-key }}-${{ hashFiles('.github/ci-tools.toml') }}
    - uses: actions/checkout@v6.0.1
    - name: Set up Python
      uses: actions/setup-python@v6.1.0
      with:
        python-version: '3.14'
        cache: pip
        cache-dependency-path: .github/ci-tools.toml
    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@v1.17.4
    - name: Install uv
      uses: astral-sh/setup-uv@v7.2.0
    - name: Install tools to test self using self-action
      uses: ./
      with:
        section: ci
      env:
        # uv will install into system
        UV_SYSTEM_PYTHON: 1
    - name: Action test
      run: |
        if ! command -v fd; then
          echo "fd not installed"
          exit 1
        fi
        if command -v typos; then
          echo "typos is installed"
          exit 1
        fi
    - name: Unit tests
      run: |
        pytest tests.py -n auto --random-order
